### ISSUE TITLE
 Cannot find module 'ionic-color-picker'.

### ISSUE THREAD

**Issue by haakon-io** [KokilaBawankar/ionic-color-picker#1] opened 2020-01-20 21:04 UTC
Tried to use your color picker but I can't seem to import it. Using Angular 8 and Ionic.

Regards

**Comment by supermafete** [comment] 2020-03-09 12:04
Same here. It seems there isn't any file or export.

**Comment by sapabg** [comment] 2020-04-10 12:58
+1

**Comment by alainm23** [comment] 2020-04-18 00:29
+1

**Comment by dberniell** [comment] 2020-04-21 16:32
+1

**Comment by dartrox21** [comment] 2020-04-27 00:08
+1

**Comment by fchristl** [comment] 2020-04-30 12:16
Same problem. If I see it correctly, the issue is that `package.json` links to `dist/index.js`, but the code is compiled to `dist/out-tsc/...`.

**Comment by KokilaBawankar** [comment] 2020-05-06 10:51
Issue is solved now, remove the old version and install the latest 1.0.0 version. Now I am closing this issue.

**Closed as completed by KokilaBawankar** 2020-05-06 10:51 UTC
